const seedCustomers = [
  {id:1,name:'瀚海供应链',short:'瀚海',contact:'陈佳宁',phone:'138 5688 1203',route:'海运整箱 · 上海—洛杉矶',monthlyVolume:'80—100 TEU',opportunityValue:680000,quoteExpiry:'2026-09-15',paymentTerm:'月结45天',status:'方案沟通',level:'重点',nextDate:'2026-09-04',nextAction:'发送华东—洛杉矶年度报价方案',activities:[{type:'线上会议',date:'09月02日 14:30',createdDate:'2026-09-02',content:'客户希望整合上海、宁波两地出口业务，重点关注美西航线舱位稳定性。',next:'整理年度框架报价与舱位保障方案'},{type:'电话沟通',date:'08月29日 10:15',createdDate:'2026-08-29',content:'确认第四季度预计出货量为每月 80—100 TEU。',next:'预约方案评审会议'}]},
  {id:2,name:'启航国际物流',short:'启航',contact:'周宇航',phone:'186 0211 8972',route:'空运 · 上海—法兰克福',monthlyVolume:'28—35 吨',opportunityValue:420000,quoteExpiry:'2026-09-10',paymentTerm:'月结45天',status:'商务谈判',level:'重点',nextDate:'2026-09-03',nextAction:'确认信用账期与服务费率',nextDone:true,completedOn:'2026-09-03',activities:[{type:'上门拜访',date:'09月01日 16:00',createdDate:'2026-09-01',content:'客户认可轨迹可视化方案，希望进一步确认账期和实施周期。',next:'与财务确认 45 天账期'}]},
  {id:3,name:'远达跨境运输',short:'远达',contact:'王思远',phone:'139 1765 4310',route:'跨境小包 · 华东—欧洲',monthlyVolume:'12万票',opportunityValue:360000,quoteExpiry:'2026-09-20',paymentTerm:'月结30天',status:'潜在客户',level:'普通',nextDate:'2026-09-06',nextAction:'首次需求访谈',activities:[{type:'微信沟通',date:'08月31日 11:20',createdDate:'2026-08-31',content:'客户正在评估跨境小包追踪系统，对多承运商轨迹整合感兴趣。',next:'发送访谈提纲'}]},
  {id:4,name:'东澜货运代理',short:'东澜',contact:'刘静',phone:'137 8890 5621',route:'海运拼箱 · 宁波—胡志明',monthlyVolume:'45 CBM',opportunityValue:180000,quoteExpiry:'2026-09-05',paymentTerm:'月结30天',status:'暂缓推进',level:'风险',nextDate:'2026-09-02',nextAction:'确认项目是否重启',activities:[{type:'电话沟通',date:'08月27日 09:40',createdDate:'2026-08-27',content:'客户因内部预算调整暂缓项目，预计九月重新评估。',next:'九月初再次联系'}]},
  {id:5,name:'中欧陆桥物流',short:'陆桥',contact:'赵可',phone:'159 0087 3026',route:'铁路 · 西安—杜伊斯堡',monthlyVolume:'36 柜',opportunityValue:510000,quoteExpiry:'2026-09-18',paymentTerm:'月结60天',status:'需求确认',level:'重点',nextDate:'2026-09-05',nextAction:'演示铁路节点追踪能力',activities:[{type:'邮件沟通',date:'09月01日 13:10',createdDate:'2026-09-01',content:'客户发来现有操作流程，核心诉求是异常节点预警。',next:'准备定制演示环境'}]},
  {id:6,name:'星港航运服务',short:'星港',contact:'沈悦',phone:'135 6401 2289',route:'海运整箱 · 上海—杰贝阿里',monthlyVolume:'50 TEU',opportunityValue:300000,quoteExpiry:'2026-09-22',paymentTerm:'月结45天',status:'潜在客户',level:'普通',nextDate:'2026-09-08',nextAction:'发送产品介绍与案例',activities:[]}
];
function loadCustomers(){try{return CargoPulseLogic.normalizeCustomers(JSON.parse(localStorage.getItem('cargopulse-customers')||'null'),seedCustomers)}catch{return CargoPulseLogic.normalizeCustomers(null,seedCustomers)}}
let customers=loadCustomers();
let selectedId=customers[0]?.id;let activeFilter='all';
const TODAY=new Date().toLocaleDateString('sv-SE');
const endDate=new Date(`${TODAY}T00:00:00`);endDate.setDate(endDate.getDate()+4);const PERIOD_END=endDate.toLocaleDateString('sv-SE');
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const {sanitizeText:clean,validatePhone,isPastDate,isDuplicateCustomer,normalizeCustomers,buildReportDates,analyzeFollowup,calculateQuality,getChannelCounts}=CargoPulseLogic;
const rowObserver=new MutationObserver(()=>$$('.customer-row').forEach(row=>{row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label',`打开客户 ${row.querySelector('.company strong')?.textContent||''}`);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();row.click()}}}));rowObserver.observe($('#customer-list'),{childList:true});
const freightObserver=new MutationObserver(()=>{const panel=$('#detail-panel'),customer=customers.find(item=>item.id===selectedId);if(!panel||!customer)return;const complete=panel.querySelector('#complete-action');if(complete&&!complete.dataset.safe){complete.dataset.safe='true';complete.onclick=()=>{const backup=JSON.parse(JSON.stringify(customers));customer.nextDone=true;customer.completedOn=TODAY;if(!save()){customers=backup;renderDetail();return}renderList();renderDetail();renderDashboard();syncQuality();toast('行动已完成并保存，KPI 已更新')}}if(panel.querySelector('.freight-card'))return;const anchor=panel.querySelector('.section-title');if(!anchor)return;const card=document.createElement('div');card.className='freight-card';const fields=[['预计月货量',customer.monthlyVolume||'待确认'],['商机金额','¥ '+Number(customer.opportunityValue||0).toLocaleString('zh-CN')],['报价有效期',customer.quoteExpiry||'待确认'],['期望账期',customer.paymentTerm||'待确认']];fields.forEach(([label,value])=>{const item=document.createElement('div'),caption=document.createElement('span'),strong=document.createElement('strong');caption.textContent=label;strong.textContent=value;item.append(caption,strong);card.append(item)});anchor.before(card)});
freightObserver.observe($('#detail-panel'),{childList:true});
$$('[data-close-dialog]').forEach(button=>button.onclick=()=>document.getElementById(button.dataset.closeDialog).close());
$('#follow-dialog').addEventListener('close',()=>{$('#follow-form').reset();$('#ai-result').classList.add('hidden');$('#ai-result').removeAttribute('data-summary')});
['content','nextAction'].forEach(name=>$('#follow-form').querySelector(`[name=${name}]`).addEventListener('input',()=>$('#ai-result').classList.add('hidden')));
function save(){try{localStorage.setItem('cargopulse-customers',JSON.stringify(customers));return true}catch{toast('保存失败：浏览器存储空间不足，数据未提交');return false}}
function setSubmitting(button,busy,label){button.disabled=busy;button.textContent=busy?'保存中…':label}
function formatDate(date){const d=new Date(date+'T00:00:00');return `${d.getMonth()+1}月${d.getDate()}日`}
function renderList(){const q=$('#global-search').value.trim().toLowerCase();const filtered=customers.filter(c=>{const text=`${c.name}${c.contact}${c.route}`.toLowerCase();const pass=activeFilter==='all'||(activeFilter==='重点'&&c.level==='重点')||(activeFilter==='风险'&&c.level==='风险')||(activeFilter==='待跟进'&&!c.nextDone&&c.nextDate<=PERIOD_END);return text.includes(q)&&pass});$('#customer-list').innerHTML=filtered.map(c=>`<article class="customer-row ${c.id===selectedId?'selected':''}" data-id="${c.id}"><div class="company"><div class="company-logo">${clean(c.short)}</div><div><strong>${clean(c.name)}</strong><small>${clean(c.contact)} · ${clean(c.phone).slice(-4)}</small></div></div><div class="cell">${clean(c.route)}</div><div class="cell"><span class="tag ${c.level==='风险'?'risk':c.level==='普通'?'neutral':''}">${clean(c.status)}</span></div><div class="cell">${c.nextDone?'<span class="completed-chip">✓ 已完成</span>':`<strong>${formatDate(c.nextDate)}</strong>`}<small>${clean(c.nextAction)}</small></div></article>`).join('');$('#empty-state').classList.toggle('hidden',filtered.length>0);$$('.customer-row').forEach(el=>el.onclick=()=>{selectedId=Number(el.dataset.id);renderList();renderDetail()});const activityCount=customers.reduce((n,c)=>n+c.activities.length,0);$('#all-total').textContent=customers.length;$('#key-count').textContent=customers.filter(c=>c.level==='重点').length;$('#week-count').textContent=activityCount;$('#pending-count').textContent=customers.filter(c=>!c.nextDone&&c.nextDate<=PERIOD_END).length;$('#overdue-count').textContent=customers.filter(c=>!c.nextDone&&c.nextDate<TODAY).length}
function renderDetail(){const c=customers.find(x=>x.id===selectedId);if(!c){$('#detail-panel').innerHTML='';return}const timeline=c.activities.length?c.activities.map(a=>`<div class="activity"><div class="activity-head"><strong>${clean(a.type)}${a.intent?' · 意向'+clean(a.intent):''}</strong><span>${clean(a.date)}</span></div><p>${clean(a.content)}</p>${a.summary?`<div class="next-action"><b>AI 摘要：</b>${clean(a.summary)}</div>`:''}<div class="next-action"><b>下一步：</b>${clean(a.next)}</div></div>`).join(''):'<div class="empty"><strong>还没有跟进记录</strong><p>新增第一条记录，开始沉淀客户信息。</p></div>';const actionState=c.nextDone?'<span class="completed-chip">✓ 已完成</span>':`<strong>${formatDate(c.nextDate)}</strong>`;$('#detail-panel').innerHTML=`<div class="detail-top"><div class="detail-company"><div class="company-logo">${clean(c.short)}</div><div><h2>${clean(c.name)}</h2><p>${clean(c.route)}</p></div></div><span class="level">${clean(c.level)}客户</span></div><div class="contact-card"><div><span>联系人</span><strong>${clean(c.contact)}</strong></div><div><span>联系电话</span><strong>${clean(c.phone)}</strong></div><div><span>当前阶段</span><strong>${clean(c.status)}</strong></div><div><span>下次行动</span>${actionState}</div></div><div class="section-title"><h3>跟进时间线</h3><span>${c.activities.length} 条记录</span></div><div class="timeline">${timeline}</div><button class="primary add-follow" id="open-follow">＋ 新增跟进</button>${c.nextDone?'':`<button class="complete-action" id="complete-action">✓ 标记“${clean(c.nextAction)}”已完成</button>`}`;$('#open-follow').onclick=()=>{const form=$('#follow-form');form.querySelector('[name=nextDate]').value=c.nextDate;form.querySelector('[name=stage]').value=c.status;$('#ai-result').classList.add('hidden');$('#follow-dialog').showModal()};if($('#complete-action'))$('#complete-action').onclick=()=>{c.nextDone=true;c.completedOn='2026-09-03';save();renderList();renderDetail();renderDashboard();syncQuality();toast('行动已完成，KPI 已更新')}}
function renderDashboard(){const all=customers.flatMap(c=>c.activities);const week=Array.from({length:7},(_,i)=>{const d=new Date(`${TODAY}T00:00:00`);d.setDate(d.getDate()-6+i);return d.toLocaleDateString('sv-SE')});const recent=all.filter(a=>week.includes(a.createdDate||TODAY));const counts=week.map(d=>recent.filter(a=>(a.createdDate||TODAY)===d).length);const max=Math.max(1,...counts);$('#bar-chart').innerHTML=week.map((d,i)=>`<div class="bar-item"><div class="bar" title="${counts[i]} 次" style="height:${Math.max(8,counts[i]/max*100)}%"></div><span>${d.slice(5).replace('-','/')} · ${counts[i]}</span></div>`).join('');$('#trend-total').textContent=`${recent.length} 次`;$('#report-range').textContent=`${week[0].slice(5).replace('-','.')} — ${week[6].slice(5).replace('-','.')}`;const defs=[['电话','电话','#0573aa'],['会议','会议','#23b8c5'],['拜访','拜访','#e9a23b'],['其他','其他','#7a89a0']];const raw=defs.map(([label,key,color])=>[label,key==='其他'?recent.filter(a=>!['电话','会议','拜访'].some(k=>a.type.includes(k))).length:recent.filter(a=>a.type.includes(key)).length,color]);const total=Math.max(1,recent.length);let cursor=0;const stops=[];raw.forEach(x=>{const start=cursor;cursor+=x[1]/total*100;stops.push(`${x[2]} ${start}% ${cursor}%`)});$('.donut').style.background=`radial-gradient(circle,#fff 50%,transparent 51%),conic-gradient(${stops.join(',')})`;$('.donut strong').textContent=recent.length;$('#channel-legend').innerHTML=raw.map(x=>`<li><i style="background:${x[2]}"></i>${x[0]} ${Math.round(x[1]/total*100)}%</li>`).join('');const attention=customers.filter(c=>!c.nextDone&&(c.level==='风险'||c.nextDate<=TODAY));$('#attention-list').innerHTML=attention.length?attention.map(c=>`<div class="attention-item"><div><strong>${clean(c.name)}</strong><small> · ${clean(c.nextAction)}</small></div><span>${c.nextDate<TODAY?'已逾期':'今天'}</span></div>`).join(''):'<div class="empty"><strong>暂无需要关注的行动</strong></div>'}
function syncQuality(){const quality=calculateQuality(customers,TODAY);[['coverage',quality.coverage],['action',quality.action],['ontime',quality.ontime]].forEach(([id,val])=>{$(`#${id}-value`).textContent=`${val}%`;$(`#${id}-progress`).value=val});return quality}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
$('.icon-button').onclick=()=>toast('暂无新通知');
const tourSteps=[
  ['从问题出发','销售跟进信息常散落在微信、电话和个人笔记中。CargoPulse 首先把客户、当前阶段和下一步行动放在同一工作区。'],
  ['快速定位客户','搜索与状态筛选帮助销售快速找到重点、待跟进或风险客户；列表直接展示下一步行动，减少遗漏。'],
  ['沉淀客户记忆','客户详情使用时间线保留每次沟通、客户意向和后续承诺，人员交接时也能快速恢复上下文。'],
  ['AI 辅助而非替代','新增跟进中的 AI 会提取需求、风险和行动建议，但必须由销售确认后保存，避免错误信息直接写入客户档案。'],
  ['形成可信 KPI','团队看板不只统计次数，还关注客户覆盖、按时完成和行动计划，并保留从指标回到原始记录的设计空间。']
];let tourIndex=0;
function renderTour(){const step=tourSteps[tourIndex];$('#tour-count').textContent=`${String(tourIndex+1).padStart(2,'0')} / ${String(tourSteps.length).padStart(2,'0')}`;$('#tour-title').textContent=step[0];$('#tour-copy').textContent=step[1];$('#tour-next').textContent=tourIndex===tourSteps.length-1?'完成导览 ✓':'下一步 →'}
$('#start-tour').onclick=()=>{tourIndex=0;renderTour();$('#tour').classList.remove('hidden')};$('#tour-close').onclick=()=>$('#tour').classList.add('hidden');$('#tour-next').onclick=()=>{if(tourIndex===tourSteps.length-1){$('#tour').classList.add('hidden');toast('导览完成，可以开始操作 Demo');return}tourIndex++;renderTour()};
$('#show-kpi-basis').onclick=()=>{const k=syncQuality();$('#kpi-basis').innerHTML=`<div class="kpi-row"><strong>按时完成率</strong><span>按计划日期完成 ${k.onTimeCompleted} / 到期 ${k.due}（已完成 ${k.completed}）</span><strong>${k.ontime}%</strong></div><div class="kpi-row"><strong>客户覆盖率</strong><span>有跟进记录客户 ${k.covered} / ${customers.length}</span><strong>${k.coverage}%</strong></div><div class="kpi-row"><strong>行动计划率</strong><span>含下一步行动记录 ${k.planned} / ${k.total}</span><strong>${k.action}%</strong></div>`;$('#kpi-dialog').showModal()};
$$('.nav-item').forEach(btn=>btn.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${btn.dataset.view}-view`).classList.add('active');$('#page-title').textContent=btn.dataset.view==='customers'?'客户管理':'团队看板';if(btn.dataset.view==='dashboard')renderDashboard()});
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>$('.search').classList.toggle('hidden',btn.dataset.view==='dashboard')));
$$('.tab').forEach(tab=>tab.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');activeFilter=tab.dataset.filter;renderList()});
$('#global-search').oninput=renderList;$('#add-customer').onclick=()=>{const form=$('#customer-form');form.reset();form.querySelector('[name=nextDate]').value=TODAY;form.querySelector('[name=quoteExpiry]').value=TODAY;$('#customer-dialog').showModal()};$('#reset-demo').onclick=()=>{if(!confirm('恢复初始演示数据？你新增的客户和跟进记录将被清除且无法撤销。'))return;const backup=customers;customers=JSON.parse(JSON.stringify(seedCustomers));selectedId=customers[0].id;activeFilter='all';if(!save()){customers=backup;selectedId=customers[0]?.id;return}renderList();renderDetail();renderDashboard();syncQuality();toast('演示数据已恢复')};
$('#ai-organize').onclick=()=>{const form=$('#follow-form');const content=form.querySelector('[name=content]').value.trim();if(content.length<10){toast('请先输入较完整的沟通内容');return}const analysis=analyzeFollowup(content,form.querySelector('[name=nextAction]').value);const result=$('#ai-result');result.innerHTML=`<div><strong>客户需求：</strong>${analysis.need}</div><div><strong>风险识别：</strong>${analysis.risk}</div><div><strong>行动建议：</strong>${analysis.action}</div><div><strong>提示：</strong>保存前请人工确认，AI 不会直接修改客户档案。</div>`;result.dataset.summary=analysis.summary;result.classList.remove('hidden')};
$('#save-follow').onclick=e=>{e.preventDefault();const form=$('#follow-form'),button=e.currentTarget;if(!form.reportValidity()||button.disabled)return;const data=new FormData(form);if(data.get('content').trim().length<10){toast('跟进内容至少填写 10 个字符');form.querySelector('[name=content]').focus();return}if(isPastDate(data.get('nextDate'),TODAY)&&!confirm('下一步行动日期早于今天，将立即形成逾期任务。仍要保存吗？'))return;const backup=JSON.parse(JSON.stringify(customers)),c=customers.find(x=>x.id===selectedId),result=$('#ai-result');setSubmitting(button,true,'保存记录');c.activities.unshift({type:data.get('type'),date:'刚刚',createdDate:TODAY,content:clean(data.get('content').trim()),intent:data.get('intent'),summary:result.classList.contains('hidden')?'':result.dataset.summary,next:clean(data.get('nextAction').trim())});c.status=data.get('stage');c.nextDate=data.get('nextDate');c.nextAction=clean(data.get('nextAction').trim());c.nextDone=false;if(!save()){customers=backup;setSubmitting(button,false,'保存记录');return}renderList();renderDetail();renderDashboard();syncQuality();setSubmitting(button,false,'保存记录');$('#follow-dialog').close();toast('跟进记录已保存，客户阶段与 KPI 已同步')};
$('#save-customer').onclick=e=>{e.preventDefault();const form=$('#customer-form'),button=e.currentTarget;if(!form.reportValidity()||button.disabled)return;const raw=Object.fromEntries(new FormData(form));if(!validatePhone(raw.phone)){toast('电话号码格式不正确');form.querySelector('[name=phone]').focus();return}const d={...raw};Object.keys(d).forEach(k=>d[k]=k==='phone'?String(d[k]).trim():clean(d[k]).trim());if(isDuplicateCustomer(customers,d.name)){toast('已存在同名客户，请先搜索确认');form.querySelector('[name=name]').focus();return}if(isPastDate(d.nextDate,TODAY)&&!confirm('首次行动日期早于今天，客户创建后将立即逾期。仍要创建吗？'))return;if(isPastDate(d.quoteExpiry,TODAY)&&!confirm('报价有效期早于今天，创建后报价将立即失效。仍要创建吗？'))return;const backup=JSON.parse(JSON.stringify(customers)),item={id:Date.now()+Math.floor(Math.random()*1000),...d,opportunityValue:Number(d.opportunityValue),nextAction:'完成首次需求访谈',nextDone:false,activities:[]};setSubmitting(button,true,'创建客户');customers.unshift(item);selectedId=item.id;if(!save()){customers=backup;selectedId=customers[0]?.id;setSubmitting(button,false,'创建客户');return}renderList();renderDetail();renderDashboard();syncQuality();setSubmitting(button,false,'创建客户');$('#customer-dialog').close();toast('新客户已创建并保存')};
renderList();renderDetail();renderDashboard();syncQuality();
